name: Publish Maven

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Extract version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 92.112.127.240 >> ~/.ssh/known_hosts

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Publish artifact
        run: ./gradlew publish --no-daemon

      - name: Finalize deploy
        run: ssh -i ~/.ssh/id_rsa root@92.112.127.240 "/usr/local/bin/maven-deploy.sh"